releasePrefix: "-"

secretEnvs:
  ALERT_AUTH_KEY: "myAlert@uthKey"
  DB_HOST: "mysql"
  DB_USER: "backup"
  DB_PASS: "b@ckupUserPa$s"
  DB_PORT: "3307"
  S3_ACCESS_KEY: "my_ak"
  S3_SECRET_KEY: "my_sk"

defaultImage: nixyslab/nxs-backup
defaultImageTag: alpine

configMaps:
  config:
    data:
      nxs-backup.conf: |-
        project_name: "My Project"
        server_name: backup-in-k8s
        server:
          metrics:
            metrics_file_path: /var/nxs-backup/nxs-backup.metrics
        notifications:
          mail:
            enabled: false
          webhooks:
          - webhook_url: "https://my-alert.com/v2/alert"
            extra_headers:
              "Auth-Key": ENV:ALERT_AUTH_KEY
            payload_message_key: "triggerMessage"
            extra_payload:
              "isEmergencyAlert":  false
        storage_connects:
        - name: my_cloud_s3
          s3_params:
            bucket_name: nxs-backup-site-dev
            access_key_id: ENV:S3_ACCESS_KEY
            secret_access_key: ENV:S3_SECRET_KEY
            endpoint: storage.cloud.net
            region: eu-central-1
        jobs:
        - job_name: backup-mysql
          type: mysql
          tmp_dir: /var/nxs-backup/dump_tmp
          sources:
          - name: mysql
            connect:
              db_host: ENV:DB_HOST
              db_port: ENV:DB_PORT
              db_user: ENV:DB_USER
              db_password: ENV:DB_PASS
            target_dbs:
            - project-db
            gzip: true
            db_extra_keys: '--opt --add-drop-database --routines --comments --create-options --quote-names --order-by-primary --hex-blob --single-transaction'
          storages_options:
          - storage_name: my_cloud_s3
            backup_path: /nxs-backup/databases
            retention:
              days: 14
              weeks: 6
              months: 6

pvcs:
  nxs-backup:
    accessModes:
      - ReadWriteMany
    size: 200Gi

cronJobs:
  nxs-backup-database-hourly:
    schedule: "0 * * * *"
    containers:
    - name: nxs-backup
      command: nxs-backup start databases
      envSecrets:
      - secret-envs
      volumeMounts:
      - name: config
        mountPath: /etc/nxs-backup
      - name: nxs-backup
        mountPath: /var/nxs-backup
    volumes:
    - type: configMap
      name: config
    - name: nxs-backup
      type: pvc
    restartPolicy: Never

deployments:
  nxs-backup-metrics:
    extraSelectorLabels:
      app: nxs-backup-metrics
    containers:
    - name: metrics
      command: nxs-backup server
      envSecrets:
      - secret-envs
      volumeMounts:
      - name: config
        mountPath: /etc/nxs-backup
      - name: nxs-backup
        mountPath: /var/nxs-backup
    volumes:
    - type: configMap
      name: config
    - name: nxs-backup
      type: pvc
    restartPolicy: Never

services:
  nxs-backup-metrics:
    ports:
    - name: http
      protocol: TCP
      port: 7979
    extraSelectorLabels:
      app: nxs-backup-metrics

serviceMonitors:
  nxs-backup:
    endpoints:
    - interval: 5m
      port: 7979
      path: /metrics
    extraSelectorLabels:
      app: nxs-backup-metrics
