name: "nxs-backup"
version:
  major: 2
  minor: 3
  patch: 0
builds:
- name: "debian-9"
  deb:
    dh_make:
    - "--copyright=gpl3"
    - "--single"
    - "--templates=../build-scope/tpls/debian-9"
    - "--yes"
    - "--createorig"
    dpkg_buildpackage:
    - "-us"
    - "-uc"
- name: "centos-7"
  rpm:
    cmake:
    - "-DRPM=on"
    - "."
    make:
    - "package"
