name: Update Docker Hub Description
on:
  push:
    branches:
    - main
    paths:
    - README.md
    - .github/workflows/dockerhub-description.yml
    - .descriptions/*.md

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    environment: secure
    steps:
    - uses: actions/checkout@v4

    - name: Docker Hub Description bin
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
        repository: nixyslab/nxs-backup-bin
        short-description: ${{ github.event.repository.description }}
        readme-filepath: .descriptions/nxs-backup-bin.md

    - name: Docker Hub Description debian
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_TOKEN }}
        repository: nixyslab/nxs-backup
        short-description: ${{ github.event.repository.description }}
        readme-filepath: .descriptions/nxs-backup.md
