name: Go test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  check-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Set version
      run: V=${{ github.ref_name }} && VT="${V#v}" && sed "s@APP_VERSION@$VT@" misc/version.go.in > misc/version.go

    - name: Build
      run: CGO_ENABLED=0 go build -v

    - name: Test
      run: go test -v ./...
